def load_map(pth_name):
    map ={
        'posec3d_2d': posec3d_2d
    }
    return map[pth_name]

posec3d_2d = {
'backbone.conv1.conv.weight': 'backbone.conv1._conv.weight',
'backbone.conv1.bn.weight': 'backbone.conv1._batch_norm.bn2d.gamma',
'backbone.conv1.bn.bias': 'backbone.conv1._batch_norm.bn2d.beta',
'backbone.conv1.bn.running_mean': 'backbone.conv1._batch_norm.bn2d.moving_mean',
'backbone.conv1.bn.running_var': 'backbone.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.conv1.bn.num_batches_tracked': '',
'backbone.layer1.0.conv1.conv.weight': 'backbone.res_layers.0.0.conv1._conv.weight',
'backbone.layer1.0.conv1.bn.weight': 'backbone.res_layers.0.0.conv1._batch_norm.bn2d.gamma',
'backbone.layer1.0.conv1.bn.bias': 'backbone.res_layers.0.0.conv1._batch_norm.bn2d.beta',
'backbone.layer1.0.conv1.bn.running_mean': 'backbone.res_layers.0.0.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer1.0.conv1.bn.running_var': 'backbone.res_layers.0.0.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.0.conv1.bn.num_batches_tracked': '',
'backbone.layer1.0.conv2.conv.weight': 'backbone.res_layers.0.0.conv2._conv.weight',
'backbone.layer1.0.conv2.bn.weight': 'backbone.res_layers.0.0.conv2._batch_norm.bn2d.gamma',
'backbone.layer1.0.conv2.bn.bias': 'backbone.res_layers.0.0.conv2._batch_norm.bn2d.beta',
'backbone.layer1.0.conv2.bn.running_mean': 'backbone.res_layers.0.0.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer1.0.conv2.bn.running_var': 'backbone.res_layers.0.0.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.0.conv2.bn.num_batches_tracked': '',
'backbone.layer1.0.conv3.conv.weight': 'backbone.res_layers.0.0.conv3._conv.weight',
'backbone.layer1.0.conv3.bn.weight': 'backbone.res_layers.0.0.conv3._batch_norm.bn2d.gamma',
'backbone.layer1.0.conv3.bn.bias': 'backbone.res_layers.0.0.conv3._batch_norm.bn2d.beta',
'backbone.layer1.0.conv3.bn.running_mean': 'backbone.res_layers.0.0.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer1.0.conv3.bn.running_var': 'backbone.res_layers.0.0.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.0.conv3.bn.num_batches_tracked': '',
'backbone.layer1.0.downsample.conv.weight': 'backbone.res_layers.0.0.downsample._conv.weight',
'backbone.layer1.0.downsample.bn.weight': 'backbone.res_layers.0.0.downsample._batch_norm.bn2d.gamma',
'backbone.layer1.0.downsample.bn.bias': 'backbone.res_layers.0.0.downsample._batch_norm.bn2d.beta',
'backbone.layer1.0.downsample.bn.running_mean': 'backbone.res_layers.0.0.downsample._batch_norm.bn2d.moving_mean',
'backbone.layer1.0.downsample.bn.running_var': 'backbone.res_layers.0.0.downsample._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.0.downsample.bn.num_batches_tracked': '',
'backbone.layer1.1.conv1.conv.weight': 'backbone.res_layers.0.1.conv1._conv.weight',
'backbone.layer1.1.conv1.bn.weight': 'backbone.res_layers.0.1.conv1._batch_norm.bn2d.gamma',
'backbone.layer1.1.conv1.bn.bias': 'backbone.res_layers.0.1.conv1._batch_norm.bn2d.beta',
'backbone.layer1.1.conv1.bn.running_mean': 'backbone.res_layers.0.1.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer1.1.conv1.bn.running_var': 'backbone.res_layers.0.1.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.1.conv1.bn.num_batches_tracked': '',
'backbone.layer1.1.conv2.conv.weight': 'backbone.res_layers.0.1.conv2._conv.weight',
'backbone.layer1.1.conv2.bn.weight': 'backbone.res_layers.0.1.conv2._batch_norm.bn2d.gamma',
'backbone.layer1.1.conv2.bn.bias': 'backbone.res_layers.0.1.conv2._batch_norm.bn2d.beta',
'backbone.layer1.1.conv2.bn.running_mean': 'backbone.res_layers.0.1.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer1.1.conv2.bn.running_var': 'backbone.res_layers.0.1.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.1.conv2.bn.num_batches_tracked': '',
'backbone.layer1.1.conv3.conv.weight': 'backbone.res_layers.0.1.conv3._conv.weight',
'backbone.layer1.1.conv3.bn.weight': 'backbone.res_layers.0.1.conv3._batch_norm.bn2d.gamma',
'backbone.layer1.1.conv3.bn.bias': 'backbone.res_layers.0.1.conv3._batch_norm.bn2d.beta',
'backbone.layer1.1.conv3.bn.running_mean': 'backbone.res_layers.0.1.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer1.1.conv3.bn.running_var': 'backbone.res_layers.0.1.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.1.conv3.bn.num_batches_tracked': '',
'backbone.layer1.2.conv1.conv.weight': 'backbone.res_layers.0.2.conv1._conv.weight',
'backbone.layer1.2.conv1.bn.weight': 'backbone.res_layers.0.2.conv1._batch_norm.bn2d.gamma',
'backbone.layer1.2.conv1.bn.bias': 'backbone.res_layers.0.2.conv1._batch_norm.bn2d.beta',
'backbone.layer1.2.conv1.bn.running_mean': 'backbone.res_layers.0.2.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer1.2.conv1.bn.running_var': 'backbone.res_layers.0.2.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.2.conv1.bn.num_batches_tracked': '',
'backbone.layer1.2.conv2.conv.weight': 'backbone.res_layers.0.2.conv2._conv.weight',
'backbone.layer1.2.conv2.bn.weight': 'backbone.res_layers.0.2.conv2._batch_norm.bn2d.gamma',
'backbone.layer1.2.conv2.bn.bias': 'backbone.res_layers.0.2.conv2._batch_norm.bn2d.beta',
'backbone.layer1.2.conv2.bn.running_mean': 'backbone.res_layers.0.2.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer1.2.conv2.bn.running_var': 'backbone.res_layers.0.2.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.2.conv2.bn.num_batches_tracked': '',
'backbone.layer1.2.conv3.conv.weight': 'backbone.res_layers.0.2.conv3._conv.weight',
'backbone.layer1.2.conv3.bn.weight': 'backbone.res_layers.0.2.conv3._batch_norm.bn2d.gamma',
'backbone.layer1.2.conv3.bn.bias': 'backbone.res_layers.0.2.conv3._batch_norm.bn2d.beta',
'backbone.layer1.2.conv3.bn.running_mean': 'backbone.res_layers.0.2.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer1.2.conv3.bn.running_var': 'backbone.res_layers.0.2.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.2.conv3.bn.num_batches_tracked': '',
'backbone.layer1.3.conv1.conv.weight': 'backbone.res_layers.0.3.conv1._conv.weight',
'backbone.layer1.3.conv1.bn.weight': 'backbone.res_layers.0.3.conv1._batch_norm.bn2d.gamma',
'backbone.layer1.3.conv1.bn.bias': 'backbone.res_layers.0.3.conv1._batch_norm.bn2d.beta',
'backbone.layer1.3.conv1.bn.running_mean': 'backbone.res_layers.0.3.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer1.3.conv1.bn.running_var': 'backbone.res_layers.0.3.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.3.conv1.bn.num_batches_tracked': '',
'backbone.layer1.3.conv2.conv.weight': 'backbone.res_layers.0.3.conv2._conv.weight',
'backbone.layer1.3.conv2.bn.weight': 'backbone.res_layers.0.3.conv2._batch_norm.bn2d.gamma',
'backbone.layer1.3.conv2.bn.bias': 'backbone.res_layers.0.3.conv2._batch_norm.bn2d.beta',
'backbone.layer1.3.conv2.bn.running_mean': 'backbone.res_layers.0.3.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer1.3.conv2.bn.running_var': 'backbone.res_layers.0.3.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.3.conv2.bn.num_batches_tracked': '',
'backbone.layer1.3.conv3.conv.weight': 'backbone.res_layers.0.3.conv3._conv.weight',
'backbone.layer1.3.conv3.bn.weight': 'backbone.res_layers.0.3.conv3._batch_norm.bn2d.gamma',
'backbone.layer1.3.conv3.bn.bias': 'backbone.res_layers.0.3.conv3._batch_norm.bn2d.beta',
'backbone.layer1.3.conv3.bn.running_mean': 'backbone.res_layers.0.3.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer1.3.conv3.bn.running_var': 'backbone.res_layers.0.3.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer1.3.conv3.bn.num_batches_tracked': '',
'backbone.layer2.0.conv1.conv.weight': 'backbone.res_layers.1.0.conv1._conv.weight',
'backbone.layer2.0.conv1.bn.weight': 'backbone.res_layers.1.0.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.0.conv1.bn.bias': 'backbone.res_layers.1.0.conv1._batch_norm.bn2d.beta',
'backbone.layer2.0.conv1.bn.running_mean': 'backbone.res_layers.1.0.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.0.conv1.bn.running_var': 'backbone.res_layers.1.0.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.0.conv1.bn.num_batches_tracked': '',
'backbone.layer2.0.conv2.conv.weight': 'backbone.res_layers.1.0.conv2._conv.weight',
'backbone.layer2.0.conv2.bn.weight': 'backbone.res_layers.1.0.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.0.conv2.bn.bias': 'backbone.res_layers.1.0.conv2._batch_norm.bn2d.beta',
'backbone.layer2.0.conv2.bn.running_mean': 'backbone.res_layers.1.0.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.0.conv2.bn.running_var': 'backbone.res_layers.1.0.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.0.conv2.bn.num_batches_tracked': '',
'backbone.layer2.0.conv3.conv.weight': 'backbone.res_layers.1.0.conv3._conv.weight',
'backbone.layer2.0.conv3.bn.weight': 'backbone.res_layers.1.0.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.0.conv3.bn.bias': 'backbone.res_layers.1.0.conv3._batch_norm.bn2d.beta',
'backbone.layer2.0.conv3.bn.running_mean': 'backbone.res_layers.1.0.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.0.conv3.bn.running_var': 'backbone.res_layers.1.0.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.0.conv3.bn.num_batches_tracked': '',
'backbone.layer2.0.downsample.conv.weight': 'backbone.res_layers.1.0.downsample._conv.weight',
'backbone.layer2.0.downsample.bn.weight': 'backbone.res_layers.1.0.downsample._conv.weight',
'backbone.layer2.0.downsample.bn.bias': 'backbone.res_layers.1.0.conv3._batch_norm.bn2d.beta',
'backbone.layer2.0.downsample.bn.running_mean': 'backbone.res_layers.1.0.downsample._batch_norm.bn2d.moving_mean',
'backbone.layer2.0.downsample.bn.running_var': 'backbone.res_layers.1.0.downsample._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.0.downsample.bn.num_batches_tracked': '',
'backbone.layer2.1.conv1.conv.weight': 'backbone.res_layers.1.1.conv1._conv.weight',
'backbone.layer2.1.conv1.bn.weight': 'backbone.res_layers.1.1.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.1.conv1.bn.bias': 'backbone.res_layers.1.1.conv1._batch_norm.bn2d.beta',
'backbone.layer2.1.conv1.bn.running_mean': 'backbone.res_layers.1.1.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.1.conv1.bn.running_var': 'backbone.res_layers.1.1.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.1.conv1.bn.num_batches_tracked': '',
'backbone.layer2.1.conv2.conv.weight': 'backbone.res_layers.1.1.conv2._conv.weight',
'backbone.layer2.1.conv2.bn.weight': 'backbone.res_layers.1.1.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.1.conv2.bn.bias': 'backbone.res_layers.1.1.conv2._batch_norm.bn2d.beta',
'backbone.layer2.1.conv2.bn.running_mean': 'backbone.res_layers.1.1.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.1.conv2.bn.running_var': 'backbone.res_layers.1.1.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.1.conv2.bn.num_batches_tracked': '',
'backbone.layer2.1.conv3.conv.weight': 'backbone.res_layers.1.1.conv3._conv.weight',
'backbone.layer2.1.conv3.bn.weight': 'backbone.res_layers.1.1.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.1.conv3.bn.bias': 'backbone.res_layers.1.1.conv3._batch_norm.bn2d.beta',
'backbone.layer2.1.conv3.bn.running_mean': 'backbone.res_layers.1.1.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.1.conv3.bn.running_var': 'backbone.res_layers.1.1.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.1.conv3.bn.num_batches_tracked': '',
'backbone.layer2.2.conv1.conv.weight': 'backbone.res_layers.1.2.conv1._conv.weight',
'backbone.layer2.2.conv1.bn.weight': 'backbone.res_layers.1.2.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.2.conv1.bn.bias': 'backbone.res_layers.1.2.conv1._batch_norm.bn2d.beta',
'backbone.layer2.2.conv1.bn.running_mean': 'backbone.res_layers.1.2.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.2.conv1.bn.running_var': 'backbone.res_layers.1.2.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.2.conv1.bn.num_batches_tracked': '',
'backbone.layer2.2.conv2.conv.weight': 'backbone.res_layers.1.2.conv2._conv.weight',
'backbone.layer2.2.conv2.bn.weight': 'backbone.res_layers.1.2.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.2.conv2.bn.bias': 'backbone.res_layers.1.2.conv2._batch_norm.bn2d.beta',
'backbone.layer2.2.conv2.bn.running_mean': 'backbone.res_layers.1.2.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.2.conv2.bn.running_var': 'backbone.res_layers.1.2.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.2.conv2.bn.num_batches_tracked': '',
'backbone.layer2.2.conv3.conv.weight': 'backbone.res_layers.1.2.conv3._conv.weight',
'backbone.layer2.2.conv3.bn.weight': 'backbone.res_layers.1.2.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.2.conv3.bn.bias': 'backbone.res_layers.1.2.conv3._batch_norm.bn2d.beta',
'backbone.layer2.2.conv3.bn.running_mean': 'backbone.res_layers.1.2.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.2.conv3.bn.running_var': 'backbone.res_layers.1.2.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.2.conv3.bn.num_batches_tracked': '',
'backbone.layer2.3.conv1.conv.weight': 'backbone.res_layers.1.3.conv1._conv.weight',
'backbone.layer2.3.conv1.bn.weight': 'backbone.res_layers.1.3.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.3.conv1.bn.bias': 'backbone.res_layers.1.3.conv1._batch_norm.bn2d.beta',
'backbone.layer2.3.conv1.bn.running_mean': 'backbone.res_layers.1.3.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.3.conv1.bn.running_var': 'backbone.res_layers.1.3.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.3.conv1.bn.num_batches_tracked': '',
'backbone.layer2.3.conv2.conv.weight': 'backbone.res_layers.1.3.conv2._conv.weight',
'backbone.layer2.3.conv2.bn.weight': 'backbone.res_layers.1.3.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.3.conv2.bn.bias': 'backbone.res_layers.1.3.conv2._batch_norm.bn2d.beta',
'backbone.layer2.3.conv2.bn.running_mean': 'backbone.res_layers.1.3.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.3.conv2.bn.running_var': 'backbone.res_layers.1.3.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.3.conv2.bn.num_batches_tracked': '',
'backbone.layer2.3.conv3.conv.weight': 'backbone.res_layers.1.3.conv3._conv.weight',
'backbone.layer2.3.conv3.bn.weight': 'backbone.res_layers.1.3.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.3.conv3.bn.bias': 'backbone.res_layers.1.3.conv3._batch_norm.bn2d.beta',
'backbone.layer2.3.conv3.bn.running_mean': 'backbone.res_layers.1.3.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.3.conv3.bn.running_var': 'backbone.res_layers.1.3.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.3.conv3.bn.num_batches_tracked': '',
'backbone.layer2.4.conv1.conv.weight': 'backbone.res_layers.1.4.conv1._conv.weight',
'backbone.layer2.4.conv1.bn.weight': 'backbone.res_layers.1.4.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.4.conv1.bn.bias': 'backbone.res_layers.1.4.conv1._batch_norm.bn2d.beta',
'backbone.layer2.4.conv1.bn.running_mean': 'backbone.res_layers.1.4.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.4.conv1.bn.running_var': 'backbone.res_layers.1.4.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.4.conv1.bn.num_batches_tracked': '',
'backbone.layer2.4.conv2.conv.weight': 'backbone.res_layers.1.4.conv2._conv.weight',
'backbone.layer2.4.conv2.bn.weight': 'backbone.res_layers.1.4.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.4.conv2.bn.bias': 'backbone.res_layers.1.4.conv2._batch_norm.bn2d.beta',
'backbone.layer2.4.conv2.bn.running_mean': 'backbone.res_layers.1.4.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.4.conv2.bn.running_var': 'backbone.res_layers.1.4.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.4.conv2.bn.num_batches_tracked': '',
'backbone.layer2.4.conv3.conv.weight': 'backbone.res_layers.1.4.conv3._conv.weight',
'backbone.layer2.4.conv3.bn.weight': 'backbone.res_layers.1.4.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.4.conv3.bn.bias': 'backbone.res_layers.1.4.conv3._batch_norm.bn2d.beta',
'backbone.layer2.4.conv3.bn.running_mean': 'backbone.res_layers.1.4.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.4.conv3.bn.running_var': 'backbone.res_layers.1.4.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.4.conv3.bn.num_batches_tracked': '',
'backbone.layer2.5.conv1.conv.weight': 'backbone.res_layers.1.5.conv1._conv.weight',
'backbone.layer2.5.conv1.bn.weight': 'backbone.res_layers.1.5.conv1._batch_norm.bn2d.gamma',
'backbone.layer2.5.conv1.bn.bias': 'backbone.res_layers.1.5.conv1._batch_norm.bn2d.beta',
'backbone.layer2.5.conv1.bn.running_mean': 'backbone.res_layers.1.5.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer2.5.conv1.bn.running_var': 'backbone.res_layers.1.5.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.5.conv1.bn.num_batches_tracked': '',
'backbone.layer2.5.conv2.conv.weight': 'backbone.res_layers.1.5.conv2._conv.weight',
'backbone.layer2.5.conv2.bn.weight': 'backbone.res_layers.1.5.conv2._batch_norm.bn2d.gamma',
'backbone.layer2.5.conv2.bn.bias': 'backbone.res_layers.1.5.conv2._batch_norm.bn2d.beta',
'backbone.layer2.5.conv2.bn.running_mean': 'backbone.res_layers.1.5.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer2.5.conv2.bn.running_var': 'backbone.res_layers.1.5.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.5.conv2.bn.num_batches_tracked': '',
'backbone.layer2.5.conv3.conv.weight': 'backbone.res_layers.1.5.conv3._conv.weight',
'backbone.layer2.5.conv3.bn.weight': 'backbone.res_layers.1.5.conv3._batch_norm.bn2d.gamma',
'backbone.layer2.5.conv3.bn.bias': 'backbone.res_layers.1.5.conv3._batch_norm.bn2d.beta',
'backbone.layer2.5.conv3.bn.running_mean': 'backbone.res_layers.1.5.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer2.5.conv3.bn.running_var': 'backbone.res_layers.1.5.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer2.5.conv3.bn.num_batches_tracked': '',
'backbone.layer3.0.conv1.conv.weight': 'backbone.res_layers.2.0.conv1._conv.weight',
'backbone.layer3.0.conv1.bn.weight': 'backbone.res_layers.2.0.conv1._batch_norm.bn2d.gamma',
'backbone.layer3.0.conv1.bn.bias': 'backbone.res_layers.2.0.conv1._batch_norm.bn2d.beta',
'backbone.layer3.0.conv1.bn.running_mean': 'backbone.res_layers.2.0.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer3.0.conv1.bn.running_var': 'backbone.res_layers.2.0.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.0.conv1.bn.num_batches_tracked': '',
'backbone.layer3.0.conv2.conv.weight': 'backbone.res_layers.2.0.conv2._conv.weight',
'backbone.layer3.0.conv2.bn.weight': 'backbone.res_layers.2.0.conv2._batch_norm.bn2d.gamma',
'backbone.layer3.0.conv2.bn.bias': 'backbone.res_layers.2.0.conv2._batch_norm.bn2d.beta',
'backbone.layer3.0.conv2.bn.running_mean': 'backbone.res_layers.2.0.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer3.0.conv2.bn.running_var': 'backbone.res_layers.2.0.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.0.conv2.bn.num_batches_tracked': '',
'backbone.layer3.0.conv3.conv.weight': 'backbone.res_layers.2.0.conv3._conv.weight',
'backbone.layer3.0.conv3.bn.weight': 'backbone.res_layers.2.0.conv3._batch_norm.bn2d.gamma',
'backbone.layer3.0.conv3.bn.bias': 'backbone.res_layers.2.0.conv3._batch_norm.bn2d.beta',
'backbone.layer3.0.conv3.bn.running_mean': 'backbone.res_layers.2.0.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer3.0.conv3.bn.running_var': 'backbone.res_layers.2.0.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.0.conv3.bn.num_batches_tracked': '',
'backbone.layer3.0.downsample.conv.weight': 'backbone.res_layers.2.0.downsample._conv.weight',
'backbone.layer3.0.downsample.bn.weight': 'backbone.res_layers.2.0.downsample._batch_norm.bn2d.gamma',
'backbone.layer3.0.downsample.bn.bias': 'backbone.res_layers.2.0.downsample._batch_norm.bn2d.beta',
'backbone.layer3.0.downsample.bn.running_mean': 'backbone.res_layers.2.0.downsample._batch_norm.bn2d.moving_mean',
'backbone.layer3.0.downsample.bn.running_var': 'backbone.res_layers.2.0.downsample._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.0.downsample.bn.num_batches_tracked': '',
'backbone.layer3.1.conv1.conv.weight': 'backbone.res_layers.2.1.conv1._conv.weight',
'backbone.layer3.1.conv1.bn.weight': 'backbone.res_layers.2.1.conv1._batch_norm.bn2d.gamma',
'backbone.layer3.1.conv1.bn.bias': 'backbone.res_layers.2.1.conv1._batch_norm.bn2d.beta',
'backbone.layer3.1.conv1.bn.running_mean': 'backbone.res_layers.2.1.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer3.1.conv1.bn.running_var': 'backbone.res_layers.2.1.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.1.conv1.bn.num_batches_tracked': '',
'backbone.layer3.1.conv2.conv.weight': 'backbone.res_layers.2.1.conv2._conv.weight',
'backbone.layer3.1.conv2.bn.weight': 'backbone.res_layers.2.1.conv2._batch_norm.bn2d.gamma',
'backbone.layer3.1.conv2.bn.bias': 'backbone.res_layers.2.1.conv2._batch_norm.bn2d.beta',
'backbone.layer3.1.conv2.bn.running_mean': 'backbone.res_layers.2.1.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer3.1.conv2.bn.running_var': 'backbone.res_layers.2.1.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.1.conv2.bn.num_batches_tracked': '',
'backbone.layer3.1.conv3.conv.weight': 'backbone.res_layers.2.1.conv3._conv.weight',
'backbone.layer3.1.conv3.bn.weight': 'backbone.res_layers.2.1.conv3._batch_norm.bn2d.gamma',
'backbone.layer3.1.conv3.bn.bias': 'backbone.res_layers.2.1.conv3._batch_norm.bn2d.beta',
'backbone.layer3.1.conv3.bn.running_mean': 'backbone.res_layers.2.1.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer3.1.conv3.bn.running_var': 'backbone.res_layers.2.1.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.1.conv3.bn.num_batches_tracked': '',
'backbone.layer3.2.conv1.conv.weight': 'backbone.res_layers.2.2.conv1._conv.weight',
'backbone.layer3.2.conv1.bn.weight': 'backbone.res_layers.2.2.conv1._batch_norm.bn2d.gamma',
'backbone.layer3.2.conv1.bn.bias': 'backbone.res_layers.2.2.conv1._batch_norm.bn2d.beta',
'backbone.layer3.2.conv1.bn.running_mean': 'backbone.res_layers.2.2.conv1._batch_norm.bn2d.moving_mean',
'backbone.layer3.2.conv1.bn.running_var': 'backbone.res_layers.2.2.conv1._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.2.conv1.bn.num_batches_tracked': '',
'backbone.layer3.2.conv2.conv.weight': 'backbone.res_layers.2.2.conv2._conv.weight',
'backbone.layer3.2.conv2.bn.weight': 'backbone.res_layers.2.2.conv2._batch_norm.bn2d.gamma',
'backbone.layer3.2.conv2.bn.bias': 'backbone.res_layers.2.2.conv2._batch_norm.bn2d.beta',
'backbone.layer3.2.conv2.bn.running_mean': 'backbone.res_layers.2.2.conv2._batch_norm.bn2d.moving_mean',
'backbone.layer3.2.conv2.bn.running_var': 'backbone.res_layers.2.2.conv2._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.2.conv2.bn.num_batches_tracked': '',
'backbone.layer3.2.conv3.conv.weight': 'backbone.res_layers.2.2.conv3._conv.weight',
'backbone.layer3.2.conv3.bn.weight': 'backbone.res_layers.2.2.conv3._batch_norm.bn2d.gamma',
'backbone.layer3.2.conv3.bn.bias': 'backbone.res_layers.2.2.conv3._batch_norm.bn2d.beta',
'backbone.layer3.2.conv3.bn.running_mean': 'backbone.res_layers.2.2.conv3._batch_norm.bn2d.moving_mean',
'backbone.layer3.2.conv3.bn.running_var': 'backbone.res_layers.2.2.conv3._batch_norm.bn2d.moving_variance',
# 'backbone.layer3.2.conv3.bn.num_batches_tracked': '',
'cls_head.fc_cls.weight': 'head.fc_cls.weight',
'cls_head.fc_cls.bias': 'head.fc_cls.bias',
}
