"""
backbone.conv1._conv.weight
backbone.conv1._batch_norm.bn2d.moving_mean
backbone.conv1._batch_norm.bn2d.moving_variance
backbone.conv1._batch_norm.bn2d.gamma
backbone.conv1._batch_norm.bn2d.beta
backbone.res_layers.0.0.conv1._conv.weight
backbone.res_layers.0.0.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.0.0.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.0.0.conv1._batch_norm.bn2d.gamma
backbone.res_layers.0.0.conv1._batch_norm.bn2d.beta
backbone.res_layers.0.0.conv2._conv.weight
backbone.res_layers.0.0.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.0.0.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.0.0.conv2._batch_norm.bn2d.gamma
backbone.res_layers.0.0.conv2._batch_norm.bn2d.beta
backbone.res_layers.0.0.conv3._conv.weight
backbone.res_layers.0.0.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.0.0.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.0.0.conv3._batch_norm.bn2d.gamma
backbone.res_layers.0.0.conv3._batch_norm.bn2d.beta
backbone.res_layers.0.0.downsample._conv.weight
backbone.res_layers.0.0.downsample._batch_norm.bn2d.moving_mean
backbone.res_layers.0.0.downsample._batch_norm.bn2d.moving_variance
backbone.res_layers.0.0.downsample._batch_norm.bn2d.gamma
backbone.res_layers.0.0.downsample._batch_norm.bn2d.beta
backbone.res_layers.0.1.conv1._conv.weight
backbone.res_layers.0.1.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.0.1.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.0.1.conv1._batch_norm.bn2d.gamma
backbone.res_layers.0.1.conv1._batch_norm.bn2d.beta
backbone.res_layers.0.1.conv2._conv.weight
backbone.res_layers.0.1.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.0.1.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.0.1.conv2._batch_norm.bn2d.gamma
backbone.res_layers.0.1.conv2._batch_norm.bn2d.beta
backbone.res_layers.0.1.conv3._conv.weight
backbone.res_layers.0.1.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.0.1.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.0.1.conv3._batch_norm.bn2d.gamma
backbone.res_layers.0.1.conv3._batch_norm.bn2d.beta
backbone.res_layers.0.2.conv1._conv.weight
backbone.res_layers.0.2.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.0.2.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.0.2.conv1._batch_norm.bn2d.gamma
backbone.res_layers.0.2.conv1._batch_norm.bn2d.beta
backbone.res_layers.0.2.conv2._conv.weight
backbone.res_layers.0.2.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.0.2.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.0.2.conv2._batch_norm.bn2d.gamma
backbone.res_layers.0.2.conv2._batch_norm.bn2d.beta
backbone.res_layers.0.2.conv3._conv.weight
backbone.res_layers.0.2.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.0.2.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.0.2.conv3._batch_norm.bn2d.gamma
backbone.res_layers.0.2.conv3._batch_norm.bn2d.beta
backbone.res_layers.0.3.conv1._conv.weight
backbone.res_layers.0.3.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.0.3.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.0.3.conv1._batch_norm.bn2d.gamma
backbone.res_layers.0.3.conv1._batch_norm.bn2d.beta
backbone.res_layers.0.3.conv2._conv.weight
backbone.res_layers.0.3.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.0.3.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.0.3.conv2._batch_norm.bn2d.gamma
backbone.res_layers.0.3.conv2._batch_norm.bn2d.beta
backbone.res_layers.0.3.conv3._conv.weight
backbone.res_layers.0.3.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.0.3.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.0.3.conv3._batch_norm.bn2d.gamma
backbone.res_layers.0.3.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.0.conv1._conv.weight
backbone.res_layers.1.0.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.0.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.0.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.0.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.0.conv2._conv.weight
backbone.res_layers.1.0.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.0.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.0.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.0.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.0.conv3._conv.weight
backbone.res_layers.1.0.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.0.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.0.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.0.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.0.downsample._conv.weight
backbone.res_layers.1.0.downsample._batch_norm.bn2d.moving_mean
backbone.res_layers.1.0.downsample._batch_norm.bn2d.moving_variance
backbone.res_layers.1.0.downsample._batch_norm.bn2d.gamma
backbone.res_layers.1.0.downsample._batch_norm.bn2d.beta
backbone.res_layers.1.1.conv1._conv.weight
backbone.res_layers.1.1.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.1.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.1.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.1.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.1.conv2._conv.weight
backbone.res_layers.1.1.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.1.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.1.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.1.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.1.conv3._conv.weight
backbone.res_layers.1.1.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.1.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.1.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.1.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.2.conv1._conv.weight
backbone.res_layers.1.2.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.2.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.2.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.2.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.2.conv2._conv.weight
backbone.res_layers.1.2.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.2.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.2.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.2.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.2.conv3._conv.weight
backbone.res_layers.1.2.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.2.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.2.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.2.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.3.conv1._conv.weight
backbone.res_layers.1.3.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.3.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.3.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.3.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.3.conv2._conv.weight
backbone.res_layers.1.3.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.3.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.3.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.3.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.3.conv3._conv.weight
backbone.res_layers.1.3.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.3.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.3.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.3.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.4.conv1._conv.weight
backbone.res_layers.1.4.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.4.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.4.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.4.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.4.conv2._conv.weight
backbone.res_layers.1.4.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.4.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.4.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.4.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.4.conv3._conv.weight
backbone.res_layers.1.4.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.4.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.4.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.4.conv3._batch_norm.bn2d.beta
backbone.res_layers.1.5.conv1._conv.weight
backbone.res_layers.1.5.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.1.5.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.1.5.conv1._batch_norm.bn2d.gamma
backbone.res_layers.1.5.conv1._batch_norm.bn2d.beta
backbone.res_layers.1.5.conv2._conv.weight
backbone.res_layers.1.5.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.1.5.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.1.5.conv2._batch_norm.bn2d.gamma
backbone.res_layers.1.5.conv2._batch_norm.bn2d.beta
backbone.res_layers.1.5.conv3._conv.weight
backbone.res_layers.1.5.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.1.5.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.1.5.conv3._batch_norm.bn2d.gamma
backbone.res_layers.1.5.conv3._batch_norm.bn2d.beta
backbone.res_layers.2.0.conv1._conv.weight
backbone.res_layers.2.0.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.2.0.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.2.0.conv1._batch_norm.bn2d.gamma
backbone.res_layers.2.0.conv1._batch_norm.bn2d.beta
backbone.res_layers.2.0.conv2._conv.weight
backbone.res_layers.2.0.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.2.0.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.2.0.conv2._batch_norm.bn2d.gamma
backbone.res_layers.2.0.conv2._batch_norm.bn2d.beta
backbone.res_layers.2.0.conv3._conv.weight
backbone.res_layers.2.0.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.2.0.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.2.0.conv3._batch_norm.bn2d.gamma
backbone.res_layers.2.0.conv3._batch_norm.bn2d.beta
backbone.res_layers.2.0.downsample._conv.weight
backbone.res_layers.2.0.downsample._batch_norm.bn2d.moving_mean
backbone.res_layers.2.0.downsample._batch_norm.bn2d.moving_variance
backbone.res_layers.2.0.downsample._batch_norm.bn2d.gamma
backbone.res_layers.2.0.downsample._batch_norm.bn2d.beta
backbone.res_layers.2.1.conv1._conv.weight
backbone.res_layers.2.1.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.2.1.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.2.1.conv1._batch_norm.bn2d.gamma
backbone.res_layers.2.1.conv1._batch_norm.bn2d.beta
backbone.res_layers.2.1.conv2._conv.weight
backbone.res_layers.2.1.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.2.1.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.2.1.conv2._batch_norm.bn2d.gamma
backbone.res_layers.2.1.conv2._batch_norm.bn2d.beta
backbone.res_layers.2.1.conv3._conv.weight
backbone.res_layers.2.1.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.2.1.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.2.1.conv3._batch_norm.bn2d.gamma
backbone.res_layers.2.1.conv3._batch_norm.bn2d.beta
backbone.res_layers.2.2.conv1._conv.weight
backbone.res_layers.2.2.conv1._batch_norm.bn2d.moving_mean
backbone.res_layers.2.2.conv1._batch_norm.bn2d.moving_variance
backbone.res_layers.2.2.conv1._batch_norm.bn2d.gamma
backbone.res_layers.2.2.conv1._batch_norm.bn2d.beta
backbone.res_layers.2.2.conv2._conv.weight
backbone.res_layers.2.2.conv2._batch_norm.bn2d.moving_mean
backbone.res_layers.2.2.conv2._batch_norm.bn2d.moving_variance
backbone.res_layers.2.2.conv2._batch_norm.bn2d.gamma
backbone.res_layers.2.2.conv2._batch_norm.bn2d.beta
backbone.res_layers.2.2.conv3._conv.weight
backbone.res_layers.2.2.conv3._batch_norm.bn2d.moving_mean
backbone.res_layers.2.2.conv3._batch_norm.bn2d.moving_variance
backbone.res_layers.2.2.conv3._batch_norm.bn2d.gamma
backbone.res_layers.2.2.conv3._batch_norm.bn2d.beta
head.fc_cls.weight
head.fc_cls.bias

"""