"""
data_bnt.moving_mean
data_bnt.moving_variance
data_bnt.gamma
data_bnt.beta
data_bnc.moving_mean
data_bnc.moving_variance
data_bnc.gamma
data_bnc.beta
st_gcn_networks.0.gcn.conv.weight
st_gcn_networks.0.gcn.conv.bias
st_gcn_networks.0.tcn.0.moving_mean
st_gcn_networks.0.tcn.0.moving_variance
st_gcn_networks.0.tcn.0.gamma
st_gcn_networks.0.tcn.0.beta
st_gcn_networks.0.tcn.2.weight
st_gcn_networks.0.tcn.3.moving_mean
st_gcn_networks.0.tcn.3.moving_variance
st_gcn_networks.0.tcn.3.gamma
st_gcn_networks.0.tcn.3.beta
st_gcn_networks.1.gcn.conv.weight
st_gcn_networks.1.gcn.conv.bias
st_gcn_networks.1.tcn.0.moving_mean
st_gcn_networks.1.tcn.0.moving_variance
st_gcn_networks.1.tcn.0.gamma
st_gcn_networks.1.tcn.0.beta
st_gcn_networks.1.tcn.2.weight
st_gcn_networks.1.tcn.3.moving_mean
st_gcn_networks.1.tcn.3.moving_variance
st_gcn_networks.1.tcn.3.gamma
st_gcn_networks.1.tcn.3.beta
st_gcn_networks.2.gcn.conv.weight
st_gcn_networks.2.gcn.conv.bias
st_gcn_networks.2.tcn.0.moving_mean
st_gcn_networks.2.tcn.0.moving_variance
st_gcn_networks.2.tcn.0.gamma
st_gcn_networks.2.tcn.0.beta
st_gcn_networks.2.tcn.2.weight
st_gcn_networks.2.tcn.3.moving_mean
st_gcn_networks.2.tcn.3.moving_variance
st_gcn_networks.2.tcn.3.gamma
st_gcn_networks.2.tcn.3.beta
st_gcn_networks.3.gcn.conv.weight
st_gcn_networks.3.gcn.conv.bias
st_gcn_networks.3.tcn.0.moving_mean
st_gcn_networks.3.tcn.0.moving_variance
st_gcn_networks.3.tcn.0.gamma
st_gcn_networks.3.tcn.0.beta
st_gcn_networks.3.tcn.2.weight
st_gcn_networks.3.tcn.3.moving_mean
st_gcn_networks.3.tcn.3.moving_variance
st_gcn_networks.3.tcn.3.gamma
st_gcn_networks.3.tcn.3.beta
st_gcn_networks.4.gcn.conv.weight
st_gcn_networks.4.gcn.conv.bias
st_gcn_networks.4.tcn.0.moving_mean
st_gcn_networks.4.tcn.0.moving_variance
st_gcn_networks.4.tcn.0.gamma
st_gcn_networks.4.tcn.0.beta
st_gcn_networks.4.tcn.2.weight
st_gcn_networks.4.tcn.3.moving_mean
st_gcn_networks.4.tcn.3.moving_variance
st_gcn_networks.4.tcn.3.gamma
st_gcn_networks.4.tcn.3.beta
st_gcn_networks.4.residual.0.weight
st_gcn_networks.4.residual.1.moving_mean
st_gcn_networks.4.residual.1.moving_variance
st_gcn_networks.4.residual.1.gamma
st_gcn_networks.4.residual.1.beta
st_gcn_networks.5.gcn.conv.weight
st_gcn_networks.5.gcn.conv.bias
st_gcn_networks.5.tcn.0.moving_mean
st_gcn_networks.5.tcn.0.moving_variance
st_gcn_networks.5.tcn.0.gamma
st_gcn_networks.5.tcn.0.beta
st_gcn_networks.5.tcn.2.weight
st_gcn_networks.5.tcn.3.moving_mean
st_gcn_networks.5.tcn.3.moving_variance
st_gcn_networks.5.tcn.3.gamma
st_gcn_networks.5.tcn.3.beta
st_gcn_networks.6.gcn.conv.weight
st_gcn_networks.6.gcn.conv.bias
st_gcn_networks.6.tcn.0.moving_mean
st_gcn_networks.6.tcn.0.moving_variance
st_gcn_networks.6.tcn.0.gamma
st_gcn_networks.6.tcn.0.beta
st_gcn_networks.6.tcn.2.weight
st_gcn_networks.6.tcn.3.moving_mean
st_gcn_networks.6.tcn.3.moving_variance
st_gcn_networks.6.tcn.3.gamma
st_gcn_networks.6.tcn.3.beta
st_gcn_networks.7.gcn.conv.weight
st_gcn_networks.7.gcn.conv.bias
st_gcn_networks.7.tcn.0.moving_mean
st_gcn_networks.7.tcn.0.moving_variance
st_gcn_networks.7.tcn.0.gamma
st_gcn_networks.7.tcn.0.beta
st_gcn_networks.7.tcn.2.weight
st_gcn_networks.7.tcn.3.moving_mean
st_gcn_networks.7.tcn.3.moving_variance
st_gcn_networks.7.tcn.3.gamma
st_gcn_networks.7.tcn.3.beta
st_gcn_networks.7.residual.0.weight
st_gcn_networks.7.residual.1.moving_mean
st_gcn_networks.7.residual.1.moving_variance
st_gcn_networks.7.residual.1.gamma
st_gcn_networks.7.residual.1.beta
st_gcn_networks.8.gcn.conv.weight
st_gcn_networks.8.gcn.conv.bias
st_gcn_networks.8.tcn.0.moving_mean
st_gcn_networks.8.tcn.0.moving_variance
st_gcn_networks.8.tcn.0.gamma
st_gcn_networks.8.tcn.0.beta
st_gcn_networks.8.tcn.2.weight
st_gcn_networks.8.tcn.3.moving_mean
st_gcn_networks.8.tcn.3.moving_variance
st_gcn_networks.8.tcn.3.gamma
st_gcn_networks.8.tcn.3.beta
st_gcn_networks.9.gcn.conv.weight
st_gcn_networks.9.gcn.conv.bias
st_gcn_networks.9.tcn.0.moving_mean
st_gcn_networks.9.tcn.0.moving_variance
st_gcn_networks.9.tcn.0.gamma
st_gcn_networks.9.tcn.0.beta
st_gcn_networks.9.tcn.2.weight
st_gcn_networks.9.tcn.3.moving_mean
st_gcn_networks.9.tcn.3.moving_variance
st_gcn_networks.9.tcn.3.gamma
st_gcn_networks.9.tcn.3.beta
fcn.weight
fcn.bias

Process finished with exit code 0




"""